Repository AlexAdvent/e-commer-website, pull requests merged in 2021-10, with the labels that each got.

#13 created footer for ur website.
  home.html
Labels: hacktoberfest-accepted

#14 Added Side bar for the website
  home.html
  sidebar.css
  sidebar.js
Labels: hacktoberfest-accepted

#16 add signup 2.0
  signinupdated/index.html
  signinupdated/script.js
  signinupdated/style.css
Labels: hacktoberfest-accepted

#17 Add files via upload
  signinupdated/Registration.html
Labels: hacktoberfest-accepted

#18 Update style.css
  signinupdated/style.css
Labels: hacktoberfest-accepted

#19 Added more items so site looks bigger
  home.html
Labels: Hacktoberfest, hactoberfest2021, hactoberfest, hacktoberfest-accepted

#21 Added proper header to site
  home.html
Labels: hactoberfest, hacktoberfest-accepted

#20 Update signin.html
  signin.html
Labels: Hacktoberfest, hactoberfest, hacktoberfest-accepted

#22 Updated readme.md
  README.md
  assets/contributors.JPG
  assets/sellit.jpg
Labels: hacktoberfest-accepted

#24 Changed page style
  login.html
  myaddsection.html
  signin.html
Labels: hacktoberfest-accepted

#25 Commit one
  home.html
Labels: hacktoberfest-accepted

#26 Added Contributing.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#32 Add files via upload
  Contact Us/README.md
  Contact Us/mob-healthy.svg
  Contact Us/mob-male.svg
  Contact Us/wave.png
Labels: Hacktoberfest, hactoberfest2021, hactoberfest, hacktoberfest-accepted

#33 Made Some Design Changes
  home.html
  sidemenu.js
Labels: hacktoberfest-accepted

#36 improved footer alignment and footer icons
  home.html
Labels: Hacktoberfest, hacktoberfest-accepted

#37 index.html
  Contact Us/index.html
Labels: hacktoberfest-accepted
