Repository AlexAdvent/e-commer-website, pull requests merged in 2022-10, with the labels that each got.

#55 Update sidemenu.css
  sidemenu.css
Labels: hacktoberfest-accepted

#54 Update sidebar.js
  sidebar.js
Labels: hacktoberfest-accepted

#53 Update login.html
  login.html
Labels: hacktoberfest-accepted

#52 Update home.html
  home.html
Labels: hacktoberfest-accepted

#57 Visual Changes and clean up
  README.md
  home.html
Labels: hacktoberfest-accepted

#56 Add contact us
  contact.html
  home.html
Labels: hacktoberfest-accepted

#58 Added Blog.Html
  blog.html
Labels: hacktoberfest-accepted

#59 add nav bar in blog.html
  blog.html
Labels: hacktoberfest-accepted

#60 login.html
  login.html
Labels: hacktoberfest-accepted

#62 Update signup.html
  signup.html
Labels: Hacktoberfest, hacktoberfest-accepted

#63 Add title in signin page
  signin.html
Labels: Hacktoberfest, hacktoberfest-accepted

#64 Update blog.html
  blog.html
Labels: Hacktoberfest, hacktoberfest-accepted

#65 Update home.html
  home.html
Labels: Hacktoberfest, hacktoberfest-accepted

#66 Update blog.html
  blog.html
Labels: Hacktoberfest, hactoberfest, hacktoberfest-accepted

#67 Update login.html
  login.html
Labels: hacktoberfest-accepted

#68 Update contact.html
  contact.html
Labels: hacktoberfest-accepted

#69 Update contact.html
  contact.html
Labels: hacktoberfest-accepted

#73 myaddsection made responsive and better
  myaddsection.html
Labels: hactoberfest

#74 Remove some error and add some code in blog.html. Improve blog.html
  blog.html
Labels: hacktoberfest-accepted

#76 add title in signin page
  signin.html
Labels: hactoberfest, hacktoberfest-accepted

#77 Update login.html
  login.html
Labels: hactoberfest, hacktoberfest-accepted

#78 Update myaddsection.html
  myaddsection.html
Labels: hactoberfest, hacktoberfest-accepted
